name: Postgresql conatiner

services:
   db:
      image: postgres:16
      environment:
         POSTGRES_USER: ${POSTGRES_USER:-postgres}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
         POSTGRES_DB: ${POSTGRES_DB:-tdd_product_catalog}
      ports:
         - "${DB_PORT:-5432}:5432"

      volumes:
         - tdd-product-catalog-data:/var/lib/postgresql/data
 
volumes:
  tdd-product-catalog-data: