name: Postgresql conatiner

services:
   db:
      image: postgres:16
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: tdd_product_catalog
      ports:
         - "5432:5432"

      volumes:
         - tdd-product-catalog-data:/var/lib/postgresql/data
 
volumes:
  tdd-product-catalog-data: